trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'flashcard-app' # Go to Azure DevOps → Project Settings → Service Connections  (Azure Resource Manager)
  appName: 'flashcard-app-service'
  javaVersion: '17'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy Spring Boot App
    steps:
      - task: Gradle@3
        displayName: Gradle Build & Test
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'clean test bootJar'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(javaVersion)
          options: '--stacktrace --info' # Adds more detail to logs
      - task: AzureWebApp@1
        displayName: Deploy to Azure Web App
        inputs:
          azureSubscription: $(azureSubscription)
          appType: 'webAppLinux'
          appName: $(appName)
          package: 'build/libs/*.jar'
